### ISSUE TITLE
Get price data from Coin Market Cap 

### ISSUE THREAD

**Issue by GianCastle** [hminaya/moneda-cli#1]
As a user, I would like to obtain data provided by the Coin Market Cap API, since with the data it provides me, I could have a more global view of the states of different crypto currencies in all Exchanges from a single perspective.

Heres the URL of Coin Market Cap
https://coinmarketcap.com/api/

BTW, I can make a PR if you wish. 💃 

Best rewards, Happy New Year and thanks for the CLI tool!

**Comment by hminaya** [comment]
Done.

<img width="507" alt="screen shot 2018-01-01 at 11 21 40 pm" src="https://user-images.githubusercontent.com/586656/34473542-93a4d3c6-ef4a-11e7-81fe-5aa32d5e954b.png">
