### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by sasikanth513** [hminaya/moneda-cli#2]
<img width="948" alt="screen shot 2018-01-07 at 8 02 10 pm" src="https://user-images.githubusercontent.com/6153816/34650340-ba31f8bc-f3e5-11e7-9e1d-04558bf29c72.png">

**Comment by hminaya** [comment]
@sasikanth513 could you please share what node.js and npm versions you are using?

**Comment by sasikanth513** [comment]
```
➜  ~ node --version
v4.8.3
➜  ~ npm --version
5.5.1
```

**Comment by hminaya** [comment]
@sasikanth513 you need at least node 6.x for it to work, I'd recommend the latest version of node and npm. You can download them at https://nodejs.org/en/
